'use strict';

const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { execFileSync } = require('node:child_process');
const ROOT = path.resolve(__dirname, '../..');
const EXTENSION = path.join(ROOT, 'extension');
const normalize = value => value.replace(/\\/g, '/');
const readJson = file => JSON.parse(fs.readFileSync(file, 'utf8'));
const unique = values => [...new Set(values)];

function plan(root = ROOT) {
  const extension = path.join(root, 'extension');
  const manifest = readJson(path.join(extension, 'manifest.base.json'));
  const registry = readJson(path.join(extension, 'modules.json')).modules;
  const files = new Map(), roots = {}, entries = [];
  const ids = new Set();
  for (const module of registry) {
    if (!/^[a-z0-9-]+$/.test(module.id) || ids.has(module.id)) throw new Error('Invalid/duplicate extension module ID');
    ids.add(module.id);
    const source = path.resolve(root, module.source);
    if (!source.startsWith(root + path.sep)) throw new Error('Module source must be inside EveOS');
    const prefix = `modules/${module.id}/`;
    const tool = readJson(path.join(source, 'manifest.json'));
    for (const key of ['permissions', 'optional_permissions', 'host_permissions', 'optional_host_permissions']) {
      manifest[key] = unique([...(manifest[key] || []), ...(tool[key] || [])]);
      if (!manifest[key].length) delete manifest[key];
    }
    for (const group of tool.content_scripts || []) {
      manifest.content_scripts ||= [];
      manifest.content_scripts.push({ ...group,
        js: group.js?.map(file => prefix + file),
        ...(group.css ? { css: group.css.map(file => prefix + file) } : {}) });
    }
    if (tool.web_accessible_resources) {
      manifest.web_accessible_resources ||= [];
      manifest.web_accessible_resources.push(...tool.web_accessible_resources.map(group => ({
        ...group, resources: group.resources.map(file => prefix + file)
      })));
    }
    const tracked = execFileSync('git', ['ls-files', '--cached', '--others', '--exclude-standard', '--', module.source],
      { cwd: root, encoding: 'utf8', windowsHide: true }).trim().split(/\r?\n/).filter(Boolean);
    for (const file of unique(tracked)) {
      if (!/\.(?:js|json|html|css|png|svg|ico|woff2?)$/i.test(file)) continue;
      const full = path.join(root, file), relative = normalize(path.relative(source, full));
      if (relative.startsWith('../') || fs.lstatSync(full).isSymbolicLink()) throw new Error('Unsafe module asset');
      files.set(prefix + relative, fs.readFileSync(full));
    }
    if (!files.has(prefix + module.entry)) throw new Error(`Missing module entry: ${module.id}`);
    roots[module.id] = prefix; entries.push({ id: module.id, entry: module.entry });
  }
  for (const group of manifest.content_scripts || []) {
    for (const file of [...(group.js || []), ...(group.css || [])]) {
      if (!files.has(file)) throw new Error(`Missing extension content asset: ${file}`);
    }
  }
  // Required host permissions already cover these optional requests.
  manifest.optional_host_permissions = (manifest.optional_host_permissions || []).filter(value =>
    !(manifest.host_permissions || []).includes(value));
  files.set('modules/config.js', Buffer.from(
    `/* Generated by npm run build:eveos-extension. */\n` +
    `globalThis.EveOSExtensionModuleRoots = ${JSON.stringify(roots)};\n` +
    `globalThis.EveOSExtensionModuleEntries = ${JSON.stringify(entries)};\n`));
  return { manifest, files, registry };
}

function inventory(files) {
  return Object.fromEntries([...files].map(([file, bytes]) => [file,
    crypto.createHash('sha256').update(bytes).digest('hex')]));
}

function audit({ assets = false } = {}) {
  const expected = plan();
  const actual = readJson(path.join(EXTENSION, 'manifest.json'));
  if (JSON.stringify(actual) !== JSON.stringify(expected.manifest)) throw new Error('Official manifest is stale; run build:eveos-extension');
  if (assets) {
    for (const [file, bytes] of expected.files) {
      const target = path.join(EXTENSION, file);
      if (!fs.existsSync(target) || !fs.readFileSync(target).equals(bytes)) {
        throw new Error(`Official extension asset is stale: ${file}; run build:eveos-extension`);
      }
    }
  }
  return expected;
}

function build() {
  const expected = plan();
  for (const [file, bytes] of expected.files) {
    const target = path.join(EXTENSION, file);
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, bytes);
  }
  fs.writeFileSync(path.join(EXTENSION, 'manifest.json'), JSON.stringify(expected.manifest, null, 2) + '\n');
  fs.writeFileSync(path.join(EXTENSION, 'modules', 'assembly.json'), JSON.stringify(inventory(expected.files), null, 2) + '\n');
  return expected;
}

if (require.main === module) {
  try {
    const result = process.argv.includes('--write') ? build() : audit({ assets: process.argv.includes('--assets') });
    console.log(`EVEOS_EXTENSION_ASSEMBLY_OK modules=${result.registry.length} assets=${result.files.size}`);
  } catch (error) { console.error(`EVEOS_EXTENSION_ASSEMBLY_FAILED: ${error.message}`); process.exitCode = 1; }
}
module.exports = { plan, build, audit, inventory };
