'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const privacy=require('../scripts/terminal-relay-privacy'),storage=require('../scripts/terminal-relay-storage'),processTools=require('../scripts/terminal-driver-process'),reports=require('../scripts/terminal-relay-report'),delivery=require('../scripts/terminal-relay-delivery');
test('provider sanitization removes user paths and common secrets',()=>{const root='C:\\Users\\alvin\\Documents\\Workspace\\EveOS',input=[root+'\\tools\\Nexus-Browser','Authorization: Bearer very-secret-token-value','api_key=sk-proj-ABCDEFGHIJKLMNOPQRSTUV','cookie: session=supersecret'].join('\n'),output=privacy.sanitizeText(input,{eveosRoot:root,userHome:'C:\\Users\\alvin'});assert.match(output,/<EVEOS_ROOT>/);assert.doesNotMatch(output,/C:\\Users\\alvin/i);assert.doesNotMatch(output,/very-secret-token-value/);assert.doesNotMatch(output,/ABCDEFGHIJKLMNOPQRSTUV/);assert.doesNotMatch(output,/supersecret/);});
test('runtime stays inside EveOS, target selection is local, and retention is bounded',()=>{const temp=fs.mkdtempSync(path.join(os.tmpdir(),'eveos-terminal-relay-'));try{storage.writeTargetSelection({id:'app-chatgpt-windows',providerId:'chatgpt-desktop',concreteTargetIdentity:{conversationTitle:'Test conversation'}},temp);assert.equal(storage.readTargetSelection(temp).target.providerId,'chatgpt-desktop');for(let index=0;index<23;index+=1){const run=storage.createRun({eveosRoot:temp,runId:'run-'+String(index).padStart(2,'0')});fs.writeFileSync(path.join(run.runDir,'touch.txt'),String(index));}const kept=storage.pruneRuns({eveosRoot:temp,keep:20}),root=storage.relayRoot(temp);assert.equal(kept.length,20);assert.ok(root.startsWith(path.resolve(temp)));assert.equal(fs.readdirSync(path.join(root,'runs')).length,20);}finally{fs.rmSync(temp,{recursive:true,force:true});}});
test('process environment disables interactive Git pagers and contains npm logs',()=>{const env=processTools.automationEnv();assert.equal(env.GIT_PAGER,'cat');assert.equal(env.PAGER,'cat');assert.equal(env.LESS,'FRX');assert.equal(env.GIT_TERMINAL_PROMPT,'0');assert.match(env.npm_config_logs_dir.replace(/\\/g,'/'),/data\/runtime\/nexus-browser\/terminal-relay\/npm-logs$/);assert.deepEqual(processTools.gitArgs(['status','--short']),['--no-pager','status','--short']);});
test('provider report is the sanitized artifact shape sent upstream',()=>{const root='C:\\Users\\alvin\\EveOS',run={eveosRoot:root,relativeDir:'data/runtime/nexus-browser/terminal-relay/runs/test'},ctx={options:{full:false,noPull:true,push:false},results:[{label:'example',status:'FAIL',exitCode:1,durationMs:10,stdout:root+'\\secret.txt\nAuthorization: Bearer abcdefghijklmnop'}]},output=reports.buildProviderReport({branch:'test',head:'abc',dirty:true},ctx,run);assert.match(output,/<EVEOS_ROOT>/);assert.doesNotMatch(output,/Authorization: Bearer abcdefghijklmnop/);assert.doesNotMatch(output,/C:\\Users\\alvin/);});
test('Base Mode exposes Terminal Relay controls but only metadata over HTTP',()=>{const root=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(root,'public','index.html'),'utf8'),ui=fs.readFileSync(path.join(root,'public','terminal-relay-ui.js'),'utf8'),server=fs.readFileSync(path.join(root,'server-http.js'),'utf8');assert.match(html,/id="terminalRelayPanel"/);assert.match(html,/terminal-relay-ui\.js/);assert.match(ui,/--local-only/);assert.match(ui,/\/terminal-relay\/status/);assert.match(server,/readLatestStatus/);assert.doesNotMatch(server,/full-local\.log|provider-report\.txt/);});

test('target refresh requires the same selected target and provider',()=>{const temp=fs.mkdtempSync(path.join(os.tmpdir(),'eveos-terminal-refresh-'));try{storage.writeTargetSelection({id:'app-chatgpt-windows',providerId:'chatgpt-desktop',pid:10,windowHandle:20,concreteTargetIdentity:{processId:10,windowHandle:20,conversationAnchor:'a'}},temp);assert.equal(storage.refreshTargetSelection({id:'app-chatgpt-windows',providerId:'other-provider',pid:10,windowHandle:20,concreteTargetIdentity:{processId:10,windowHandle:20,conversationAnchor:'a'}},temp),false);assert.equal(storage.refreshTargetSelection({id:'other-target',providerId:'chatgpt-desktop',pid:10,windowHandle:20,concreteTargetIdentity:{processId:10,windowHandle:20,conversationAnchor:'a'}},temp),false);const refreshed=storage.refreshTargetSelection({id:'app-chatgpt-windows',providerId:'chatgpt-desktop',pid:10,windowHandle:20,concreteTargetIdentity:{processId:10,windowHandle:20,conversationAnchor:'b',conversationAnchors:['a','b']}},temp);assert.equal(refreshed.target.concreteTargetIdentity.conversationAnchor,'b');}finally{fs.rmSync(temp,{recursive:true,force:true});}});
test('terminal relay rejects synthetic selection before native dispatch',()=>{const live={id:'app-chatgpt-windows',providerId:'chatgpt-desktop',pid:10,windowHandle:20,concreteTargetIdentity:{processId:10,windowHandle:20,conversationAnchor:'live'}};assert.throws(()=>delivery.verifyAndAdvance({target:{id:'app-chatgpt-windows',providerId:'chatgpt-desktop',pid:null,windowHandle:null,concreteTargetIdentity:{deliveryScope:'synthetic'}}},live),(error)=>error.code==='TERMINAL_RELAY_BINDING_STALE');});
test('terminal relay advances rolling anchors only when exact native continuity is proven',()=>{const selection={target:{id:'app-chatgpt-windows',providerId:'chatgpt-desktop',pid:10,windowHandle:20,concreteTargetIdentity:{processId:10,windowHandle:20,conversationAnchor:'a',conversationAnchors:['a']}}};const live={id:'app-chatgpt-windows',providerId:'chatgpt-desktop',pid:10,windowHandle:20,concreteTargetIdentity:{processId:10,windowHandle:20,conversationAnchor:'b',conversationAnchors:['a','b']}};const advanced=delivery.verifyAndAdvance(selection,live);assert.equal(advanced.concreteTargetIdentity.conversationAnchor,'b');assert.deepEqual(advanced.concreteTargetIdentity.conversationAnchors,['a','b']);});
