'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),runner=require('../app-targets/winapp-runner');

test('read-only UI inspect retries a transient stale element and then succeeds',async()=>{let calls=0;const exec=async()=>{calls+=1;if(calls===1)return{ok:false,stdout:'{"error":{"code":"stale_element","message":"Element is no longer accessible"}}',stderr:'',exitCode:1,processErrorCode:null,errorMessage:'',signal:null};return{ok:true,stdout:'{"windows":[]}',stderr:'',exitCode:0,processErrorCode:null,errorMessage:'',signal:null};};const result=await runner.runJson(['ui','inspect','-w','123'],{command:'winapp',exec,transientRetries:2});assert.equal(result.ok,true);assert.equal(calls,2);});

test('timeout-killed visible inspect retries once with a shallower tree',async()=>{const depths=[];let calls=0;const exec=async(_command,args)=>{calls+=1;const at=args.indexOf('--depth');depths.push(at>=0?Number(args[at+1]):null);if(calls===1)return{ok:false,stdout:'',stderr:'',exitCode:null,processErrorCode:null,errorMessage:'Command failed',signal:'SIGTERM',killed:true};return{ok:true,stdout:'{"windows":[]}',stderr:'',exitCode:0,processErrorCode:null,errorMessage:'',signal:null,killed:false};};const result=await runner.runJson(['ui','inspect','-w','123','--depth','12','--hide-offscreen'],{command:'winapp',exec,transientRetries:1});assert.equal(result.ok,true);assert.deepEqual(depths,[12,8]);});

test('exhausted inspect timeout is classified explicitly',async()=>{const exec=async()=>({ok:false,stdout:'',stderr:'',exitCode:null,processErrorCode:null,errorMessage:'Command failed',signal:'SIGTERM',killed:true});await assert.rejects(()=>runner.runJson(['ui','inspect','-w','123','--depth','12','--hide-offscreen'],{command:'winapp',exec,transientRetries:1}),(error)=>{assert.equal(error.code,'APP_UIA_INSPECT_TIMEOUT');assert.equal(error.detail.signal,'SIGTERM');assert.equal(error.detail.killed,true);assert.equal(error.detail.args.includes('--hide-offscreen'),true);return true;});});

test('active visible inspect outranks queued discovery work',()=>{assert.ok(runner.commandPriority(['ui','inspect','-w','1','--hide-offscreen'])>runner.commandPriority(['ui','inspect','-w','1']));assert.ok(runner.commandPriority(['ui','inspect','-w','1'])>runner.commandPriority(['ui','list-windows','-a','ChatGPT']));assert.ok(runner.commandPriority(['ui','invoke','send'])>runner.commandPriority(['ui','inspect','-w','1','--hide-offscreen']));});

test('mutating UI commands never retry stale-element failures automatically',async()=>{let calls=0;const exec=async()=>{calls+=1;return{ok:false,stdout:'{"error":{"code":"stale_element","message":"Element is no longer accessible"}}',stderr:'',exitCode:1,processErrorCode:null,errorMessage:'',signal:null};};const result=await runner.runJson(['ui','invoke','send-button'],{command:'winapp',exec,allowFailure:true});assert.equal(result.ok,false);assert.equal(calls,1);});

test('non-transient inspect failures are not replayed',async()=>{let calls=0;const exec=async()=>{calls+=1;return{ok:false,stdout:'{"error":{"code":"access_denied","message":"Denied"}}',stderr:'',exitCode:1,processErrorCode:null,errorMessage:'',signal:null};};const result=await runner.runJson(['ui','inspect','-w','123'],{command:'winapp',exec,allowFailure:true});assert.equal(result.ok,false);assert.equal(calls,1);});

test('inspect transport errors preserve process error identity and use the deep-inspect buffer',async()=>{let observed=0;const exec=async(_c,_a,o)=>{observed=o.maxBuffer;return{ok:false,stdout:'',stderr:'',exitCode:null,processErrorCode:'ERR_CHILD_PROCESS_STDIO_MAXBUFFER',errorMessage:'stdout maxBuffer length exceeded',signal:null};};await assert.rejects(()=>runner.runJson(['ui','inspect','-w','123'],{command:'winapp',exec,transientRetries:0}),(error)=>{assert.match(error.message,/maxBuffer/i);assert.equal(error.code,'ERR_CHILD_PROCESS_STDIO_MAXBUFFER');assert.equal(error.detail.processErrorCode,'ERR_CHILD_PROCESS_STDIO_MAXBUFFER');assert.equal(error.detail.exitCode,null);return true;});assert.equal(observed,runner.INSPECT_MAX_BUFFER);});
