/* EveOS Manifest Styles */
window.EveModuleManifestParts = window.EveModuleManifestParts || {};
window.EveModuleManifestParts.styles = [
        // UI Modules
        'css/v1_folder.css?v=c5c9278d6b7d',
        'js/modules/ui/sidebar.css?v=faa983433240',
        'js/modules/ui/tab-nav-history.css?v=4f81e57c076d',
        'js/modules/ui/dashboard/dashboard.css?v=849489501c27',
        'js/modules/ui/dashboard/unidex-view.css?v=1bc1d2625977',
        'js/modules/ui/dashboard/unidex-view.base.css?v=4052e2bb18de',
        'js/modules/ui/dashboard/unidex-view.entries.css?v=8076052d0a03',
        'js/modules/ui/dashboard/unidex-view.theme.css?v=ee2ee1506598',
        'js/modules/ui/dashboard/unidex-view.responsive.css?v=d91545d649a0',
        'js/modules/ui/dashboard/categories/focused-card.css?v=59b60b3b1fe9',
        'js/modules/ui/dashboard/dock.css?v=73612c59242a',
        'js/modules/ui/bulk-toolbar.css?v=96280de435e3',
        'js/modules/ui/scratchpad.css?v=9bbaaf7b7f97',
        'js/modules/ui/context-menus/styles.css?v=eff29ba2e1a2',
        'js/modules/ui/inline-prompt.css?v=25e57c724fb1',
        'js/modules/features/scraper/ui/loading-indicator/loading-indicator.css?v=9911440b79bb',

        // Feature Modules
        'js/modules/features/widgets.css?v=262b88b018bb',
        'js/modules/features/bookmark-identifiers.css?v=033cdf9df7f5',
        'js/modules/features/search.css?v=1ef6863cfe4d',
        'js/modules/features/header-controls/hc.css?v=7d9f1b3d370c',
        'js/modules/features/search-advanced/sa.css?v=e5359e43d15d',
        'js/modules/features/api-search/search-results.css?v=0f19aaf776c7',
        'js/modules/features/api-search/card-settings.css?v=92f933ce0339',
        'js/modules/features/sources/sources.css?v=3977633a0d51',
        'js/modules/features/library/library.css?v=dc4880952f86',
        'css/modules/constellation-map.css?v=d6851f24f100',

        // --- Scraper Feature Styles (Ported) ---
        'js/modules/features/scraper/core/styles/variables.css?v=e5775dcc0dc0',
        'js/modules/features/scraper/core/styles/base.css?v=d220ee98f342',
        'js/modules/features/scraper/core/styles/dark-mode.css?v=59ae3a9f0cfe',
        'js/modules/features/scraper/ui/styles/shared-highlight.css?v=584497ada25c',
        'js/modules/features/scraper/ui/result-display/result-display.css?v=9704e3c8933f',
        'js/modules/features/scraper/ui/tab-manager/tab-manager.css?v=cff2859d9fab',
        'js/modules/features/scraper/ui/popup-manager/popup-manager.css?v=990758239421',
        'js/modules/features/scraper/ui/module-status/ui-module-status.css?v=2adeffed59f2',
        'js/modules/features/scraper/ui/styles/layout-controls.css?v=3574ff5ed64d',
        'js/modules/features/scraper/ui/dropdown-handler/dropdown.css?v=e90220776350',
        'js/modules/features/scraper/ui/styles/app-layout.css?v=5bb3f93d4e25',
        'js/modules/features/scraper/ui/styles/legacy-enhancements.css?v=f159c58c1eb7',
        'js/modules/features/scraper/ui/styles/inline-overrides.css?v=97ae731eddc6',
        'js/modules/features/scraper/ui/styles/badges.css?v=80fc677172fc',
        'js/modules/features/scraper/ui/search-controls/toggle-switches.css?v=a5045300eb90',
        'js/modules/features/scraper/ui/styles/control-center.css?v=bb1c9c86d6ab',
        'js/modules/features/scraper/ui/styles/domain-manager.css?v=63b4ff592979',
        'js/modules/features/scraper/ui/styles/article-cards.css?v=fe8d62990254',
        'js/modules/features/scraper/ui/result-display/cached-results.css?v=8ce31c3c1d33',
        'js/modules/features/scraper/ui/result-display/result-layouts.css?v=499e1157ff07',
        'js/modules/features/scraper/ui/result-display/result-card.css?v=9a00b2fa2510',
        'js/modules/features/scraper/ui/result-display/result-grid.css?v=33a731240cb7',
        'js/modules/features/scraper/ui/result-display/result-container.css?v=3e5bd83d8737',
        'js/modules/features/scraper/ui/styles/failsafe.css?v=05449ef1babb',
        'js/modules/features/scraper/ui/styles/fallback-forms.css?v=f529593e8239',
        'js/modules/features/scraper/ui/styles/layout-overrides.css?v=d4518dd2aa59',
        'js/modules/features/scraper/discovery/styles/google-search-ui.css?v=80db9ab6992e',
        'js/modules/features/scraper/discovery/styles/entry-list.css?v=ed3d60840e1c',
        'js/modules/features/scraper/discovery/styles/wikipedia-section.css?v=062d0a12af51',
        'js/modules/features/scraper/discovery/styles/fandom-search.css?v=1304814a27d4',
        'js/modules/features/scraper/discovery/styles/google-search-internal.css?v=d8dc0a868554',
        'js/modules/features/scraper/discovery/styles/wiki-listing.css?v=0e06f7642491',
        'js/modules/features/scraper/discovery/system/discovery.css?v=d850f0309ba8',
        'js/modules/features/scraper/discovery/styles/domain-entry.css?v=5581f3cca303',
        'js/modules/features/scraper/discovery/styles/google-search-scraper.css?v=fb99a8195701',
        'js/modules/features/scraper/discovery/styles/google-knowledge-panel.css?v=460c03f0cbe5',
        'js/modules/features/scraper/discovery/styles/empty-states.css?v=ed609dc57d29',
        'js/modules/features/scraper/discovery/styles/google-search-errors.css?v=370a648ca465',
        'js/modules/features/scraper/features/wiki-manager.css?v=233a2df8e1e9',
        'js/modules/features/scraper/features/search-manager.css?v=15fed7ff2bb7',
        'js/modules/features/scraper/features/cache-visualization.css?v=870cc78ade91',
        'js/modules/features/scraper/search/google-cse/google-cse-embedded.css?v=5120f89efeca',
        'js/modules/features/scraper/search/google-cse/google-cse-layout.css?v=b7aca49f49b4',
        'js/modules/features/scraper/search/google-cse/google-cse-results.css?v=6a6d8d738182',
        'js/modules/features/scraper/search/google-cse/google-cse-overrides.css?v=c85f964ba614',
        'js/modules/features/scraper/search/shared/search-forms.css?v=145885da8e0c',
        'js/modules/features/scraper/utils/styles/utility.css?v=004d88d8637d',

        // Modal Modules
        'js/modules/modals/modals.css?v=c5e73ca3e548',

        // Gemini Integration Styles
        'css/modules/gemini/main_css_files.css?v=c97bd0a2e86e',
        'css/modules/gemini/audio_playback_ui/audio_player.css?v=99ae2f02d14a',
        'css/modules/gemini/base_styles_ui/body_styles.css?v=61b84ae7cb3c',
        'css/modules/gemini/button_group_ui/button_group.css?v=6af4affa4571',
        'css/modules/gemini/canvas_ui/canvas_element.css?v=2cea636c699f',
        'css/modules/gemini/chat_log_ui/chat_log.css?v=ff3b18ab2e8d',
        'css/modules/gemini/chat_message_ui/chat_message.css?v=ad54455db16e',
        'css/modules/gemini/chat_popup_ui/chat_popup.css?v=73999234b440',
        'css/modules/gemini/gemini_link_surfaces.css?v=1347004cfabb',
        'css/modules/gemini/layout_ui/app_container.css?v=29c237a323f0',
        'css/modules/gemini/layout_ui/demo_content.css?v=d41915643d50',
        'css/modules/gemini/layout_ui/large_screen_layout.css?v=e68584064f32',
        'css/modules/gemini/mdl_components_ui/mdl_buttons.css?v=93d66f8888ce',
        'css/modules/gemini/mdl_components_ui/mdl_layout_header.css?v=ce7b454400af',
        'css/modules/gemini/previous_history_ui/previous_history.css?v=5df32b5eb9d2',
        'css/modules/gemini/text_input_ui/send_button.css?v=b36b6657a823',
        'css/modules/gemini/text_input_ui/text_input.css?v=c2d6908ff7f9',
        'css/modules/gemini/theme_ui/theme_variables.css?v=a6c8d66fe1d1',
        'css/modules/gemini/video_player_ui/video_player.css?v=52e5cc06c004',
        'css/modules/gemini/video_player_ui/video_section.css?v=58212b5a9667',
        'css/modules/gemini/voice_input_ui/voice_select.css?v=5298c746960f',
        'css/modules/gemini/gemini_collapsible.css?v=72ddabfb5837',
];
