'use strict';
const { execFile } = require('node:child_process');
const DEFAULT_TIMEOUT_MS=15000, DEFAULT_MAX_BUFFER=4*1024*1024, INSPECT_MAX_BUFFER=32*1024*1024;
let resolved=null,resolvedAt=0;
function execFileAsync(file,args,options={}){return new Promise((resolve)=>{const maxBuffer=options.maxBuffer||DEFAULT_MAX_BUFFER;execFile(file,args,{encoding:'utf8',windowsHide:true,timeout:options.timeoutMs||DEFAULT_TIMEOUT_MS,maxBuffer,env:options.env||process.env},(error,stdout='',stderr='')=>resolve({ok:!error,error,stdout:String(stdout||''),stderr:String(stderr||''),exitCode:typeof error?.code==='number'?error.code:error?null:0,processErrorCode:typeof error?.code==='string'?error.code:null,errorMessage:error?.message||'',signal:error?.signal||null,maxBuffer}));});}
async function resolveCommand({env=process.env,now=Date.now(),exec=execFileAsync}={}){const configured=String(env.NEXUS_WINAPP_CLI||env.BROWSER_AI_BRIDGE_WINAPP_CLI||'').trim();if(configured)return configured;if(process.platform!=='win32')return '';if(resolved&&now-resolvedAt<30000)return resolved;const found=await exec('where.exe',['winapp'],{timeoutMs:3000,env});resolved=found.ok?found.stdout.split(/\r?\n/).map((line)=>line.trim()).find(Boolean)||'':'';resolvedAt=now;return resolved;}
const TRANSIENT_INSPECT_CODES=new Set(['stale_element','element_not_available','uia_element_not_available','rpc_e_call_rejected']);
function transientInspectFailure(args,result,json){if(result?.ok||args?.[0]!=='ui'||args?.[1]!=='inspect')return false;const code=String(json?.code||json?.error?.code||result?.processErrorCode||'').toLowerCase();const message=String(json?.message||json?.error?.message||result?.stderr||result?.errorMessage||result?.stdout||'').toLowerCase();return TRANSIENT_INSPECT_CODES.has(code)||/stale[_ ]element|no longer accessible|element.+not available|rpc.+rejected/.test(message);}
function parseJson(text){const trimmed=String(text||'').trim();if(!trimmed)return null;try{return JSON.parse(trimmed);}catch{const lines=trimmed.split(/\r?\n/).map((line)=>line.trim()).filter(Boolean);for(let index=lines.length-1;index>=0;index-=1){try{return JSON.parse(lines[index]);}catch{}}return null;}}
function defaultMaxBuffer(args=[]){return args?.[0]==='ui'&&args?.[1]==='inspect'?INSPECT_MAX_BUFFER:DEFAULT_MAX_BUFFER;}
async function runJson(args,{timeoutMs=DEFAULT_TIMEOUT_MS,env=process.env,exec=execFileAsync,command=null,allowFailure=false,transientRetries=null,maxBuffer=null}={}){const executable=command||await resolveCommand({env,exec});if(!executable){const error=new Error('Microsoft winapp CLI is not installed or not on PATH.');error.code='APP_BRIDGE_HELPER_MISSING';error.detail={install:'winget install Microsoft.winappcli --source winget'};throw error;}const argv=[...args];if(!argv.includes('--json'))argv.push('--json');const defaultRetries=args?.[0]==='ui'&&args?.[1]==='inspect'?3:0;const retries=transientRetries==null?defaultRetries:Math.max(0,Number(transientRetries)||0);const bufferLimit=Math.max(1024,Number(maxBuffer)||defaultMaxBuffer(args));let result=null,json=null;for(let attempt=0;attempt<=retries;attempt+=1){result=await exec(executable,argv,{timeoutMs,env,maxBuffer:bufferLimit});json=parseJson(result.stdout);if(!transientInspectFailure(args,result,json)||attempt>=retries)break;await new Promise((resolve)=>setTimeout(resolve,80*(attempt+1)));}if(!result.ok&&!allowFailure){const message=json?.message||json?.error?.message||result.stderr.trim()||result.errorMessage||result.stdout.trim()||(result.processErrorCode?'winapp failed ('+result.processErrorCode+')':'')||'winapp exited with code '+result.exitCode;const error=new Error(String(message).slice(0,1000));error.code=json?.code||json?.error?.code||result.processErrorCode||'APP_BRIDGE_COMMAND_FAILED';error.detail={args:argv,exitCode:result.exitCode,processErrorCode:result.processErrorCode||null,signal:result.signal||null,stdoutChars:result.stdout.length,stderrChars:result.stderr.length,maxBuffer:bufferLimit,json};throw error;}return{...result,json,command:executable,args:argv,maxBuffer:bufferLimit};}
async function availability(options={}){if(process.platform!=='win32')return{available:false,code:'APP_BRIDGE_WINDOWS_ONLY',platform:process.platform};const command=await resolveCommand(options);return command?{available:true,command}:{available:false,code:'APP_BRIDGE_HELPER_MISSING',install:'winget install Microsoft.winappcli --source winget'};}
function resetCache(){resolved=null;resolvedAt=0;}
module.exports={DEFAULT_TIMEOUT_MS,DEFAULT_MAX_BUFFER,INSPECT_MAX_BUFFER,execFileAsync,resolveCommand,parseJson,defaultMaxBuffer,transientInspectFailure,runJson,availability,resetCache};
